version: '3.8'

services:
  postgres:
    container_name: plataforma_videos
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=plataforma_videos_db